# Add some packages
- name: Install PHP and some related packages
  vars:
    packages:
      - zip
      - unzip
      - php
      - php-fpm
      - php-cli
      - php-curl
      - php-xml
      - php-zip
      - php-mbstring
  apt:
    pkg: "{{ packages }}"
    update_cache: yes
    state: latest

# Remove packages
- name: Remove apache2
  vars:
    packages:
      - apache2
  apt:
    pkg: "{{ packages }}"
    state: absent
