- name: Install Certbot PPA
  apt_repository:
    repo: ppa:certbot/certbot

- name: Install Certbot
  vars:
    packages:
      - software-properties-common
      - certbot
      - python-certbot-nginx

  apt:
    pkg: "{{ packages }}"
    update_cache: yes
    state: latest
